/**
 * Weapon stats for all 9 weapons and unlock requirements.
 * Fire rate is in rounds per second. Projectile speed in cm/s.
 * @module shared/constants/WeaponConstants
 */

import type { WeaponId, WeaponStats, WeaponUnlockRequirement } from "../types";

/** Stats for every weapon in the game. */
export const WEAPON_STATS: Record<WeaponId, WeaponStats> = {
    // --- Pistols ---
    usp: {
        id: "usp",
        name: "USP-45",
        category: "pistol",
        damage: 34,
        fireRate: 6.0,
        projectileSpeed: 40000,
        projectileSize: 4.0,
        magazineSize: 12,
        magazineCount: 4,
        fireMode: "semi",
        reloadTime: 1.5,
        modelFile: "usp.glb",
        audioFile: "pistol.mp3",
        muzzleOffset: { x: 1.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 80,
        tpScale: 0.10,
        tpRotation: { x: 0, y: Math.PI, z: Math.PI / 2 },
        tpPosition: { x: 0, y: 0.1, z: 0.025 },
        ragdollImpulse: 800,
    },
    m9: {
        id: "m9",
        name: "M9",
        category: "pistol",
        damage: 28,
        fireRate: 7.5,
        projectileSpeed: 63000,
        projectileSize: 4.0,
        magazineSize: 15,
        magazineCount: 4,
        fireMode: "semi",
        reloadTime: 1.4,
        modelFile: "m9.glb",
        audioFile: "pistol.mp3",
        muzzleOffset: { x: 2.0, y: 0.60, z: -2.0 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 80,
        tpScale: 0.10,
        tpRotation: { x: 0, y: Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 700,
    },
    eagle: {
        id: "eagle",
        name: "Desert Eagle",
        category: "pistol",
        damage: 55,
        fireRate: 3.5,
        projectileSpeed: 57000,
        projectileSize: 5.0,
        magazineSize: 7,
        magazineCount: 3,
        fireMode: "semi",
        reloadTime: 1.8,
        modelFile: "eagle.glb",
        audioFile: "pistol.mp3",
        muzzleOffset: { x: 1.6, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 85,
        tpScale: 0.10,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1200,
    },

    // --- Assault Rifles ---
    ak47: {
        id: "ak47",
        name: "AK-47",
        category: "rifle",
        damage: 35,
        fireRate: 5.0,
        projectileSpeed: 80000,
        projectileSize: 4.5,
        magazineSize: 30,
        magazineCount: 3,
        fireMode: "automatic",
        reloadTime: 2.2,
        modelFile: "ak47.glb",
        audioFile: "rifle.mp3",
        muzzleOffset: { x: 0, y: -0.1, z: -2.5 },
        muzzleRotation: { x: 0, y: Math.PI, z: 0 },
        modelRotation: { x: 0, y: Math.PI, z: 0 },
        modelPosition: { x: 0, y: 1, z: 12 },
        dropScale: 70,
        tpScale: 0.08,
        tpRotation: { x: 0, y: Math.PI, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1000,
    },
    m4a1: {
        id: "m4a1",
        name: "M4A1",
        category: "rifle",
        damage: 30,
        fireRate: 12.0,
        projectileSpeed: 85000,
        projectileSize: 4.5,
        magazineSize: 30,
        magazineCount: 3,
        fireMode: "automatic",
        reloadTime: 2.0,
        modelFile: "m4a1.glb",
        audioFile: "rifle.mp3",
        muzzleOffset: { x: 3.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 70,
        tpScale: 0.08,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 900,
    },
    scar: {
        id: "scar",
        name: "SCAR",
        category: "rifle",
        damage: 38,
        fireRate: 10.0,
        projectileSpeed: 88000,
        projectileSize: 4.5,
        magazineSize: 20,
        magazineCount: 3,
        fireMode: "automatic",
        reloadTime: 2.3,
        modelFile: "scar.glb",
        audioFile: "rifle.mp3",
        muzzleOffset: { x: 3.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 70,
        tpScale: 0.08,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1100,
    },

    // --- Snipers ---
    intervention: {
        id: "intervention",
        name: "Intervention",
        category: "sniper",
        damage: 95,
        fireRate: 1.0,
        projectileSpeed: 120000,
        projectileSize: 5.0,
        magazineSize: 5,
        magazineCount: 3,
        fireMode: "semi",
        reloadTime: 3.0,
        modelFile: "intervention.glb",
        audioFile: "sniper.mp3",
        muzzleOffset: { x: 3.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 60,
        tpScale: 0.07,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1500,
    },
    "50cal": {
        id: "50cal",
        name: "Barrett .50 Cal",
        category: "sniper",
        damage: 100,
        fireRate: 0.8,
        projectileSpeed: 130000,
        projectileSize: 6.0,
        magazineSize: 10,
        magazineCount: 2,
        fireMode: "semi",
        reloadTime: 3.5,
        modelFile: "50cal.glb",
        audioFile: "sniper.mp3",
        muzzleOffset: { x: 3.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 65,
        tpScale: 0.07,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1800,
    },
    svd: {
        id: "svd",
        name: "SVD",
        category: "sniper",
        damage: 75,
        fireRate: 2.5,
        projectileSpeed: 110000,
        projectileSize: 5.0,
        magazineSize: 10,
        magazineCount: 3,
        fireMode: "semi",
        reloadTime: 2.5,
        modelFile: "svd.glb",
        audioFile: "sniper.mp3",
        muzzleOffset: { x: 3.5, y: 0.60, z: 0.1 },
        muzzleRotation: { x: 0, y: Math.PI / 2, z: 0 },
        modelRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        modelPosition: { x: 0, y: 0, z: 0 },
        dropScale: 65,
        tpScale: 0.07,
        tpRotation: { x: 0, y: -Math.PI / 2, z: 0 },
        tpPosition: { x: 0, y: 0, z: 0 },
        ragdollImpulse: 1400,
    },
};

/**
 * Weapon unlock progression. Weapons are unlocked when the player
 * reaches the specified level. Ordered by unlock level.
 */
export const WEAPON_UNLOCK_REQUIREMENTS: WeaponUnlockRequirement[] = [
    { weaponId: "usp", unlockLevel: 1 },
    { weaponId: "m9", unlockLevel: 3 },
    { weaponId: "ak47", unlockLevel: 5 },
    { weaponId: "m4a1", unlockLevel: 8 },
    { weaponId: "eagle", unlockLevel: 10 },
    { weaponId: "scar", unlockLevel: 13 },
    { weaponId: "intervention", unlockLevel: 16 },
    { weaponId: "svd", unlockLevel: 20 },
    { weaponId: "50cal", unlockLevel: 25 },
];

/**
 * XP required to reach each level. Index 0 = level 1.
 * Uses a quadratic curve: XP(n) = 100 * n^1.5
 * This gives early levels quickly and slows progression at higher levels.
 */
export const XP_PER_LEVEL: number[] = Array.from({ length: 30 }, (_, i) =>
    Math.round(100 * Math.pow(i + 1, 1.5))
);

/** XP awarded per kill. */
export const XP_PER_KILL: number = 100;
